apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: postgres-db
spec:
  replicas: 1
  selector:
    deploymentconfig: postgres-db
  template:
    metadata:
      labels:
        deploymentconfig: postgres-db
    spec:
      containers:
      - image: postgres:11
        imagePullPolicy: Always
        name: postgres-db
        ports:
        - containerPort: 5432
          protocol: TCP
        #volumen montado en la direccion de postgress
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-db-volume
        env: #Variables, mirar en la documentacion de odoo
         - name: POSTGRES_PASSWORD
           value: "secret"
         - name: POSTGRES_USER
           value: "odoo"
         - name: POSTGRES_DB
           value: "postgres"
      volumes:
      - emptyDir: {} #crea un volumen no persistente que desaparece al teminar el pod
        name: postgres-db-volume #El mismo que el volumeMouth
  test: false
  triggers:
  - type: ConfigChange
